#!/bin/bash

response="404"
url="https://jaiminisbox.com/reader/read/one-piece-2/en/0/963/page/1"
while [ "$response" != "200" ]
do
    let rand=($RANDOM % 2)
    response=$(curl -s -o /dev/null -w "%{http_code}" $url)
    if [ $rand -gt 0 ] ; then
	echo -e "\033[31m" $response "\033[0m"
    else
	echo -e "\033[33m" $response "\033[0m"
    fi
done

echo "SUCCESS !"

open -a "Google Chrome" $url
